/* Constants needed by CORDIC algorithm. 
 *
 * To regenerate the constants, 
 * 	delete everything after #ifdef 
 * 	run `cc cordic_consts.c -lm -DREGEN`  
 * 	run `a.out >> cordic_consts.c` 
 *
 */

/* working with IEEE doubles, means there are 53 bits
 * of mantissa
 */
#define MAXBITS	53

#ifdef REGEN
#include <stdio.h>
#include <math.h>

static double invGain1;
static double invGain2;
static double atanTable[MAXBITS];
static double atanhTable[MAXBITS];
static double gain1Cordic();
static double gain2Cordic();

void cordit1(double* x0, double* y0, double* z0, double vecmode)
{
    double t;
    double x, y, z;
    int i;
    t = 1;
    x = *x0; y = *y0; z = *z0;
    for (i = 0; i < MAXBITS; ++i) {
	double x1;
	if (vecmode >= 0 && y < vecmode || vecmode<0  && z >= 0) {
	    x1 = x - y*t;
	    y = y + x*t;
	    z = z - atanTable[i];
	}
	else {
	    x1 = x + y*t;
	    y = y - x*t;
	    z = z + atanTable[i];
	}
	x = x1;
	t /= 2;
    }
    *x0 = x;
    *y0 = y;
    *z0 = z;
}
void cordit2(double* x0, double* y0, double* z0, double vecmode)
{
    double t;
    double x, y, z;
    int i;
    t = 0.5;
    x = *x0; y = *y0; z = *z0;
    int k = 3;
    for (i = 0; i < MAXBITS; ++i) {
	double x1;
	int j;
	for (j = 0; j < 2; ++j) {
	    if (vecmode >= 0 && y < 0 || vecmode<0  && z >= 0) {
		x1 = x + y*t;
		y = y + x*t;
		z = z - atanhTable[i];
	    }
	    else {
		x1 = x - y*t;
		y = y - x*t;
		z = z + atanhTable[i];
	    }
	    x = x1;
	    if (k) {
		--k;
		break;
	    }
	    else k = 3;
	}
	t /= 2;
    }
    *x0 = x;
    *y0 = y;
    *z0 = z;
}

static double gain1Cordic() {
    double x, y, z;
    x = 1;
    y = 0;
    z = 0;
    cordit1(&x, &y, &z, -1);
    return x;
}

double gain2Cordic() {
    double x, y, z;
    x = 1;
    y = 0;
    z = 0;
    cordit2(&x, &y, &z, -1);
    return x;
}

void initCordic() {
    double t = 1;
    int i;
    for (i = 0; i < MAXBITS; ++i) {
	atanTable[i] = atan(t);
	t /= 2;
	atanhTable[i] = 0.5*log((1+t)/(1-t));
    }
	gain1Cordic();
	gain2Cordic();
    invGain1 = 1/gain1Cordic();
    invGain2 = 1/gain2Cordic();
}

int main(void) {
	initCordic();
	printf("\n// Autogenerated code.\n");
	printf("#define MAXBITS %i\n", MAXBITS);
	printf("const double invGain1 = %a;\n", invGain1);
	printf("const double invGain2 = %a;\n", invGain2);
	printf("const double gain1Cordic = %a;\n", gain1Cordic); 
	printf("const double gain2Cordic = %a;\n", gain2Cordic);
	printf("const double atanTable[MAXBITS] = { ");
	for(int idx=0; idx<MAXBITS; idx++) printf("%a, ", atanTable[idx]);
	printf("};\n");
	printf("const double atanhTable[MAXBITS] = { ");
	for(int idx=0; idx<MAXBITS; idx++) printf("%a, ", atanhTable[idx]);
	printf("};\n");
	return 0;
}
#endif


// Autogenerated code.
#define MAXBITS 53
const double invGain1 = 0x1.36e9db5086bcep-1;
const double invGain2 = 0x1.3520fb0e00ff4p+0;
const double gain1Cordic = 0x1.3520fb0e00ff4p+0;
const double gain2Cordic = 0x1.3520fb0e00ff4p+0;
const double atanTable[MAXBITS] = { 0x1.921fb54442d18p-1, 0x1.dac670561bb4fp-2, 0x1.f5b75f92c80ddp-3, 0x1.fd5ba9aac2f6ep-4, 0x1.ff55bb72cfdeap-5, 0x1.ffd55bba97625p-6, 0x1.fff555bbb729bp-7, 0x1.fffd555bbba97p-8, 0x1.ffff5555bbbb7p-9, 0x1.ffffd5555bbbcp-10, 0x1.fffff55555bbcp-11, 0x1.fffffd55555bcp-12, 0x1.ffffff555555cp-13, 0x1.ffffffd555556p-14, 0x1.fffffff555555p-15, 0x1.fffffffd55555p-16, 0x1.ffffffff55555p-17, 0x1.ffffffffd5555p-18, 0x1.fffffffff5555p-19, 0x1.fffffffffd555p-20, 0x1.ffffffffff555p-21, 0x1.ffffffffffd55p-22, 0x1.fffffffffff55p-23, 0x1.fffffffffffd5p-24, 0x1.ffffffffffff5p-25, 0x1.ffffffffffffdp-26, 0x1.fffffffffffffp-27, 0x1p-27, 0x1p-28, 0x1p-29, 0x1p-30, 0x1p-31, 0x1p-32, 0x1p-33, 0x1p-34, 0x1p-35, 0x1p-36, 0x1p-37, 0x1p-38, 0x1p-39, 0x1p-40, 0x1p-41, 0x1p-42, 0x1p-43, 0x1p-44, 0x1p-45, 0x1p-46, 0x1p-47, 0x1p-48, 0x1p-49, 0x1p-50, 0x1p-51, 0x1p-52, };
const double atanhTable[MAXBITS] = { 0x1.193ea7aad030bp-1, 0x1.058aefa811452p-2, 0x1.015891c9eaef9p-3, 0x1.005588ad375acp-4, 0x1.001558891aedep-5, 0x1.000555888ad2cp-6, 0x1.0001555888913p-7, 0x1.000055558887bp-8, 0x1.0000155558908p-9, 0x1.0000055555885p-10, 0x1.0000015555489p-11, 0x1.0000005555549p-12, 0x1.0000001555555p-13, 0x1.0000000555155p-14, 0x1.00000001554d5p-15, 0x1.0000000055545p-16, 0x1.0000000015553p-17, 0x1.0000000015555p-18, 0x1.fffffffffaaabp-20, 0x1.fffffffffeaabp-21, 0x1.ffffffffffaabp-22, 0x1.ffffffffffeabp-23, 0x1.fffffffffffabp-24, 0x1.fffffffffffebp-25, 0x1.ffffffffffffbp-26, 0x1.fffffffffffffp-27, 0x1.0000001ffffffp-27, 0x1.ffffffep-29, 0x1.fffffffp-30, 0x1.fffffff8p-31, 0x1.fffffffcp-32, 0x1.fffffffep-33, 0x1.ffffffffp-34, 0x1.ffffffff8p-35, 0x1.ffffffffcp-36, 0x1.ffffffffep-37, 0x1.fffffffffp-38, 0x1.fffffffff8p-39, 0x1.fffffffffcp-40, 0x1.fffffffffep-41, 0x1.ffffffffffp-42, 0x1.ffffffffff8p-43, 0x1.ffffffffffcp-44, 0x1.ffffffffffep-45, 0x1.fffffffffffp-46, 0x1.fffffffffff8p-47, 0x1.fffffffffffcp-48, 0x1.fffffffffffep-49, 0x1.ffffffffffffp-50, 0x1.ffffffffffff8p-51, 0x1.ffffffffffffcp-52, 0x1.ffffffffffffep-53, 0x1.fffffffffffffp-54, };
